default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV["RAILS_MAX_THREADS"] { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: <%= ENV["DB_USERNAME"] %>
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DB_DEV"] %>

test:
  <<: *default
  username: <%= ENV["DB_USERNAME"] %>
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DB_TEST"] %>

production:
  primary:
    <<: *default
    database: chessbuilder_prod
  cache:
    <<: *default
    database: chessbuilder_prod_cache
  queue:
    <<: *default
    database: chessbuilder_prod_queue
  cable:
    <<: *default
    database: chessbuilder_prod_cable