default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_MAX_THREADS"] { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: <%= ENV["DB_USERNAME"] %>
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DB_DEV"] %>

test:
  <<: *default
  username: <%= ENV["DB_USERNAME"] %>
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DB_TEST"] %>

production:
  primary: &primary_production
    <<: *default
    database: chessbuilder_prod
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  cache:
    <<: *primary_production
    database: chessbuilder_prod_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: chessbuilder_prod_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: chessbuilder_prod_cable
    migrations_paths: db/cable_migrate